INSERT INTO team (name, stadium_name, stadium_capacity)
VALUES ('Arsenal', 'Emirates Stadium', 60704),
       ('Aston Villa', 'Villa Park', 42918),
       ('Bournemouth', 'Vitality Stadium', 11307),
       ('Brentford', 'Gtech Community Stadium', 17250),
       ('Brighton and Hove Albion', 'American Express Stadium', 31876),
       ('Burnley', 'Turf Moor', 21744),
       ('Chelsea', 'Stamford Bridge', 40173),
       ('Crystal Palace', 'Selhurst Park', 25194),
       ('Everton', 'Hill Dickinson Stadium', 52888),
       ('Fulham', 'Craven Cottage', 24500),
       ('Leeds United', 'Elland Road', 37608),
       ('Liverpool', 'Anfield', 61276),
       ('Manchester City', 'Etihad Stadium', 52900),
       ('Manchester United', 'Old Trafford', 74197),
       ('Newcastle United', 'St James'' Park', 52258),
       ('Nottingham Forest', 'City Ground', 30404),
       ('Sunderland', 'Stadium of Light', 49000),
       ('Tottenham Hotspur', 'Tottenham Hotspur Stadium', 62850),
       ('West Ham United', 'London Stadium', 62500),
       ('Wolverhampton Wanderers', 'Molineux Stadium', 31750);